# Generated by Django 5.1.3 on 2024-11-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
