# Generated by Django 5.1.3 on 2025-01-29 22:30

import utils.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=510)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=75, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.misc.product_image_directory_path)),
                ('available_amount', models.PositiveIntegerField(default=1)),
                ('sold_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='products', to='product.tag')),
            ],
        ),
    ]
