# Generated by Django 5.1.3 on 2024-11-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_tag_alter_order_product_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
